import { DM_Sans } from 'next/font/google';
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { shadesOfPurple } from '@clerk/themes'

const dm = DM_Sans({ subsets: ['latin'] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider dynamic appearance={{
      baseTheme: shadesOfPurple,
    }}>
    <html lang="en">
      <body className={`${dm.className} antialiased text-white bg-slate-900`}>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
